### ISSUE TITLE
Using vue-cli 3.0  with vue.config.js

### ISSUE THREAD

**Issue by greenpdx** [phegman/vue-mapbox-gl#25]
I am getting a error trying to install mapbox-gl using webpack. vue-cli 3.0 has changed the webpack structure.  How do I get mapbox-gl installed?
The extended question is how do I install other mapbox plugins?

```
// vue.config.js
module.exports = {
  chainWebpack: config => {
    config
      .plugin('mapboxgl')
      .use(require('mapbox-gl'))
  }
}
```
ReferenceError: self is not defined
    at Object.254 (/home/ubuntu/map1/node_modules/mapbox-gl/dist/mapbox-gl.js:509:29)
    at s (/home/ubuntu/map1/node_modules/mapbox-gl/dist/mapbox-gl.js:1:684)
    at /home/ubuntu/map1/node_modules/mapbox-gl/dist/mapbox-gl.js:1:735
    at Object.252../window (/home/ubuntu/map1/node_modules/mapbox-gl/dist/mapbox-gl.js:505:25)
    at s (/home/ubuntu/map1/node_modules/mapbox-gl/dist/mapbox-gl.js:1:684)
    at /home/ubuntu/map1/node_modules/mapbox-gl/dist/mapbox-gl.js:1:735
    at Object.73.../package.json (/home/ubuntu/map1/node_modules/mapbox-gl/dist/mapbox-gl.js:146:75)
    at s (/home/ubuntu/map1/node_modules/mapbox-gl/dist/mapbox-gl.js:1:684)
    at e (/home/ubuntu/map1/node_modules/mapbox-gl/dist/mapbox-gl.js:1:855)
    at /home/ubuntu/map1/node_modules/mapbox-gl/dist/mapbox-gl.js:1:873
    at i (/home/ubuntu/map1/node_modules/mapbox-gl/dist/mapbox-gl.js:1:150)
    at Object.<anonymous> (/home/ubuntu/map1/node_modules/mapbox-gl/dist/mapbox-gl.js:1:386)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)

**Comment by phegman** [comment]
Hi Shaun,

I just tried it out and I am having some issues as well. I would think this would work: 

```
// vue.config.js
module.exports = {
  configureWebpack: {
    plugins: [
      new webpack.ProvidePlugin({
        mapboxgl: 'mapbox-gl'
      })
    ]
  }
}
```

But it doesn't seem to work like it did with the older vue-cli. I will keep playing around with it, but if anybody has any insight please let us know!

Best,
Pete

**Comment by phegman** [comment]
Hi Shaun,

I played around with this a bit more and the above should work I just forgot `var webpack = require('webpack');` at the top of the config. So the full `vue.config.js` should look like this:

```
var webpack = require('webpack');

module.exports = {
  lintOnSave: true,
  configureWebpack: {
    plugins: [
      new webpack.ProvidePlugin({
        mapboxgl: 'mapbox-gl'
      })
    ]
  }
}
```

Hope that helps!

**Comment by NiQ-B** [comment]
@phegman the below did not work for me in vue-cli 3.0.0-rc.10
See chainWebpack below.
```
var webpack = require('webpack');

module.exports = {
  configureWebpack: {
    plugins: [
      new webpack.ProvidePlugin({
        mapboxgl: 'mapbox-gl'
      })
    ]
  }
}
```
```
var webpack = require('webpack')

chainWebpack: config => {
    config
      .plugin('mapboxgl')
      .use(webpack.ProvidePlugin, [{ mapboxgl: 'mapbox-gl' }])
```
